# Train config
data_csv: /content/drive/MyDrive/Диплом/Папка с кодами/Для написания в диплом/carotaje_lib/Train.csv

lr: 0.001
epochs: 20
batch_size: 256
callback_epochs: 30

status: train
output: /content/drive/MyDrive/Диплом/Папка с кодами/Для написания в диплом/carotaje_lib/Results/Exp_NN/Exp_1

